In [4]:
A = [[1, 4, 5], 
    [-5, 8, 9]]
print(A)

[[1, 4, 5], [-5, 8, 9]]


In [6]:
import numpy as np
a = np.array([[1, 2, 3],[1, 4, 5]])
print(a)

[[1 2 3]
 [1 4 5]]


In [11]:
print(a*A)
print(np.sin(1))

[[ 1  8 15]
 [-5 32 45]]
0.8414709848078965


In [82]:
# Parameters
from numpy.linalg import inv

m1   = 6; #[kg]
m2  = 3; #[kg]
lc  = 0.0983; #[m]
I1   = 0.26; #[m]
g   = 9.81; #[m/s^2]
c = 39;
c_t = 4;
stepamp = 0.5;
k = 40;
theta = 0;
thetadot = 0;
x = 1;
xdot = 0;

M = [[(m1+m2), (m2*(lc)*np.cos(theta))],
     [(m2*lc*np.cos(theta)), (m2*(lc**2) + I1)]]
C = [[c*xdot + k*x - (m2*(thetadot**2)*lc*np.sin(theta))], [m2*g*lc*np.sin(theta)+ c_t*thetadot]]
# print(M,C)
G = -np.asmatrix(inv(M))*C;
B = np.asmatrix(inv(M));
print(G)

[[-4.59819387]
 [ 4.69225099]]


In [83]:
G.shape

(2, 1)

In [87]:
f = 0
tf = 0
U = [[f],
     [tf]]
twodot = G + B*U
x2dot = twodot[0]
theta2dot = twodot[1]
print(twodot)
print(x2dot)
print(theta2dot)

[[-4.59819387]
 [ 4.69225099]]
[[-4.59819387]]
[[4.69225099]]


In [88]:
U.shape

AttributeError: 'list' object has no attribute 'shape'

In [89]:
twodot.shape

(2, 1)

In [90]:
C.shape

AttributeError: 'list' object has no attribute 'shape'